all:
	cd common/tinyxml && make && cd -;
	cd common/jsoncpp && make && cd -;
	cd common && make && cd -;
	cd match && make &&cd -;
	cd server && make && cd -;
	cd client && make && cd -;
	cd interface && make && cd -;
	cd tools && make && cd -;
clean:
	cd common/tinyxml && make clean && cd -;
	cd common/jsoncpp && make clean && cd -;
	cd common && make clean && cd -;
	cd match && make clean &&cd -;
	cd server && make clean && cd -;
	cd client && make clean && cd -;
	cd interface && make clean && cd -;
	cd tools && make clean && cd -;

